In [0]:
#read df
dfEmp = spark.read.format("csv") \
.options(header='true', delimiter = ',') \
.load("/mnt/files/Sample_data4jOIN.csv")

dfDep = spark.read.format("csv") \
.options(header='true', delimiter = ',') \
.load("/mnt/files/Department.csv")

In [0]:
from pyspark.sql.functions import col
dfEmp.join(dfDep,dfEmp.Department_id == dfDep.Department_id, "inner")\
.select(col("Employee_id"),dfEmp.Department_id,dfDep.Department_id, dfDep.Name, dfEmp.First_Name).show()

In [0]:
dfEmp.join(dfDep, dfEmp.Department_id == dfDep.Department_id, "left")\
.select(col("Employee_id"),dfEmp.Department_id, dfDep.Department_id, dfDep.Name, dfEmp.First_Name).show()

In [0]:
dfEmp.join(dfDep, dfEmp.Department_id == dfDep.Department_id, "right")\
.select(col("Employee_id"),dfEmp.Department_id, dfDep.Department_id, dfDep.Name, dfEmp.First_Name).show()

In [0]:
dfEmp.join(dfDep, dfEmp.Department_id == dfDep.Department_id, "full")\
.select(col("Employee_id"),dfEmp.Department_id, dfDep.Department_id, dfDep.Name, dfEmp.First_Name).show()

In [0]:
dfEmp.createOrReplaceTempView("EMP")
dfDep.createOrReplaceTempView("DEPT")

In [0]:
query1 = spark.sql("Select * from EMP E INNER JOIN Dept D on E.Department_id = D.Department_id")
query1.show()

In [0]:
query1 = spark.sql("Select * from EMP E LEFT JOIN Dept D on E.Department_id = D.Department_id")
query1.show()

In [0]:
query1 = spark.sql("Select * from EMP E FULL JOIN Dept D on E.Department_id = D.Department_id")
query1.show()